- name: ansible-role-linux-logstash
  src: git+https://github.com/goldstrike77/ansible-role-linux-opendistro
  version: origin/master

- name: ansible-role-linux-nginx
  src: git+https://github.com/goldstrike77/ansible-role-linux-nginx
  version: origin/master