---
- name: Creating ElasticSearch & LogStash storage folder.
  file:
    dest: '{{ opendistro_path }}/{{ item }}'
    state: 'directory'
    owner: '{{ item }}'
    group: '{{ item }}'
    mode: '0750'
  loop:
    - 'elasticsearch'
    - 'logstash'

- name: Creating LogStash configuration folder.
  file:
    dest: '/etc/logstash/{{ item }}'
    state: 'directory'
    owner: 'logstash'
    group: 'logstash'
    mode: '0750'
  loop:
    - 'conf.d'
    - 'template'
    - 'patterns'

- name: Geolocation database download.
  unarchive:
    src: "http://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=SdCj43scfhnayMbp&suffix=tar.gz"
    dest: '/etc/logstash'
    owner: 'logstash'
    group: 'logstash'
    mode: '0755'
    extra_opts: [--strip-components=1]
    exclude:
      - 'COPYRIGHT.txt'
      - 'LICENSE.txt'
      - 'README.txt'
    remote_src: 'yes'
    validate_certs: 'no'
  register: opendistro_geo_file_download
  until: opendistro_geo_file_download is succeeded
  retries: 5
  delay: 2

- name: Configure kernel parameters.
  sysctl:
    name: '{{ item.variable }}'
    value: '{{ item.value }}'
    state: 'present'
    reload: 'yes'
    sysctl_set: 'yes'
    sysctl_file: '/etc/sysctl.d/20-sysctl.conf'
  loop: '{{ opendistro_kernel_parameters }}'

- name: Open Distro configuration file transfer.
  template:
    src: '{{ item.src }}.j2'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.owner }}'
    mode: '{{ item.mode }}'
  loop: '{{ opendistro_conf }}'
  notify:
    - Restart ElasticSearch service.

- name: Kibana configuration file transfer.
  template:
    src: 'kibana.yml.j2'
    dest: '/etc/kibana/kibana.yml'
    owner: 'kibana'
    group: 'kibana'
    mode: '640'
  notify:
    - Restart Kibana service.

- name: Open Distro internal users password outputs.
  template:
    src: 'opendistro_internal_users.passwd.j2'
    dest: '/tmp/opendistro_internal_users.passwd'
    mode: '0600'
    owner: 'root'
    group: 'root'
  when: opendistro_servers[0] in ansible_default_ipv4.address
  no_log: true
