---
- name: Install the ElasticSearch exporter packages.
  package:
    name: '{{ opendistro_exporter_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 5
  delay: 2

- name: ElasticSearch exporter configure file transfer.
  template:
    src: 'elasticsearch_exporter.default.j2'
    dest: '/etc/default/elasticsearch_exporter'
    owner: 'prometheus'
    group: 'prometheus'
    mode: '0640'
  notify:
    - Restart ElasticSearch exporter service.
