---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_os_family }}.yml'

- name: Gather ElasticSearch node variables for cluster.
  set_fact:
    opendistro_servers: "\
      {% set _opendistro_servers = [] %}\
      {% for host in groups[group_names[0]] %}\
        {% set _opendistro_cluster = opendistro_cluster | default('', true) %}\
        {% if ( _opendistro_cluster == opendistro_cluster) %}\
          {% if _opendistro_servers.append(hostvars[host]['ansible_host']) %}{% endif %}\
        {% endif %}\
      {% endfor %}\
      {{ _opendistro_servers }}"
  when: opendistro_servers is not defined or opendistro_servers | length < 1

- name: Check if ElasticSearch data exists.
  stat:
    path: '{{ opendistro_path }}/elasticsearch/nodes'
  register: opendistro_es_result

- name: Open Distro for ElasticSearch operation.
  block:
    - name: Include firewall tasks.
      include: 'firewall.yml'
    - name: Include tasks for specific OS.
      include: '{{ ansible_os_family }}.yml'
    - name: Include certificate tasks.
      include: 'certificates.yml'
    - name: Include configuration tasks.
      include: 'configureation.yml'
    - name: Force the handler to run immediately.
      meta: flush_handlers
  when:
    - not opendistro_es_result.stat.exists

- name: Include ElasticSearch exporter tasks.
  include: 'exporter.yml'
  when: exporter_is_install | bool

- name: Registered with HashiCorp Consul.
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool
