---
- name: Include firewall tasks.
  include: 'firewall.yml'

- name: Include tasks for specific OS.
  include: '{{ ansible_os_family }}.yml'

- name: Include Configureation operation.
  include: 'configureation.yml'

- name: Include certificate tasks.
  include: 'certificates.yml'

- name: Check if ElasticSearch data exists.
  stat:
    path: '{{ opendistro_path }}/elasticsearch/nodes'
  register: opendistro_es_result

- name: Include configuration tasks.
  include: 'opendistro.yml'
  when: not opendistro_es_result.stat.exists

- name: Include Kibana tasks.
  include: 'kibana.yml'

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Include ElasticSearch exporter tasks.
  include: 'exporter.yml'
  when: exporter_is_install | bool

- name: Registered with HashiCorp Consul.
  include: 'register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Include Index State Management tasks.
  include: 'ISM.yml'
  when: opendistro_servers[0] in ansible_default_ipv4.address

- name: Include LogStash operation.
  include: 'logstash.yml'
